# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Kream_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kream_demo
  pod 'KakaoSDKCommon'  # 카카오 공통 모듈
  pod 'KakaoSDKAuth'    # 카카오 인증
  pod 'KakaoSDKUser'    # 카카오 유저

end
